
eureka:
  client:
    serviceUrl:
      defaultZone: http://aronim-cloud-registry.marathon.mesos:8761/eureka/

spring:
  redis:
    host: aronim-cloud-redis.marathon.mesos
    port: 6379
  rabbitmq:
    host: aronim-cloud-rabbitmq.marathon.mesos
    port: 5672
    username: kdc
    password: kdc
    virtualHost: kdc
  resources:
    cachePeriod: 604800 # 7 days